Run it tests in native mode
quarkiverse/quarkus-operator-sdk pull request #178
Opened 2021-12-24 17:38 UTC by scrocquesel

This will allow to discover errors like https://github.com/quarkiverse/quarkus-operator-sdk/issues/175

I pushed first without the update to 2.6.1 that fix the VersionInfo serialization error. Build should failed.

2021-12-24 23:18 UTC, scrocquesel commented
There is an extension in the integration-tests that allows the VersionInfo to be unserialized. The sample is not working while the integration test passed :(

2021-12-29 20:10 UTC, scrocquesel commented
Adding OperatorSDKResource.java to the sample fix the issue. I have no clue as to why VersionInfo is added to reflection items in this case.
Should we investigate more on this now that the main branch has been updated ?

2021-12-31 13:09 UTC, scrocquesel commented
I guess that a new version should be released (quarkus, fabric.io, sdk are all aligned) and continue investigation latter.

2022-01-03 08:52 UTC, metacosm requested changes

2022-01-03 08:52 UTC, metacosm commented on .github/workflows/build.yml
> +        run: mvn -B formatter:validate verify -Dnative --file pom.xml
This should be done in a different job, so that we can run both native and jvm tests to make sure we cover everything

2022-01-03 12:56 UTC, scrocquesel commented
To me, it does both already. Jvm build and test, then native compilation and native test.

________________________________
From: Chris Laprun ***@***.***>
Sent: Monday, January 3, 2022 9:52:26 AM
To: quarkiverse/quarkus-operator-sdk ***@***.***>
Cc: Sébastien Crocquesel ***@***.***>; Author ***@***.***>
Subject: Re: [quarkiverse/quarkus-operator-sdk] Run it tests in native mode (PR #178)


@metacosm requested changes on this pull request.

________________________________

In .github/workflows/build.yml<https://github.com/quarkiverse/quarkus-operator-sdk/pull/178#discussion_r777350824>:

> @@ -53,5 +53,5 @@ jobs:
           key: maven-repo-${{ runner.os }}-${{ steps.get-date.outputs.date }}

       - name: Build with Maven
-        run: mvn -B formatter:validate verify --file pom.xml
+        run: mvn -B formatter:validate verify -Dnative --file pom.xml


This should be done in a different job, so that we can run both native and jvm tests to make sure we cover everything

—
Reply to this email directly, view it on GitHub<https://github.com/quarkiverse/quarkus-operator-sdk/pull/178#pullrequestreview-842558644>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVDTYHGCQRSJG5U4HLRKRNDUUFPUVANCNFSM5KW4VA5Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-01-03 13:45 UTC, metacosm commented
Ah yes, my bad. What else is needed for this PR, then?

2022-01-03 13:47 UTC, scrocquesel commented
Nothing.

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
From: Sébastien Crocquesel ***@***.***>
Sent: Monday, January 3, 2022 1:56:53 PM
To: quarkiverse/quarkus-operator-sdk ***@***.***>
Subject: Re: [quarkiverse/quarkus-operator-sdk] Run it tests in native mode (PR #178)

To me, it does both already. Jvm build and test, then native compilation and native test.

________________________________
From: Chris Laprun ***@***.***>
Sent: Monday, January 3, 2022 9:52:26 AM
To: quarkiverse/quarkus-operator-sdk ***@***.***>
Cc: Sébastien Crocquesel ***@***.***>; Author ***@***.***>
Subject: Re: [quarkiverse/quarkus-operator-sdk] Run it tests in native mode (PR #178)


@metacosm requested changes on this pull request.

________________________________

In .github/workflows/build.yml<https://github.com/quarkiverse/quarkus-operator-sdk/pull/178#discussion_r777350824>:

> @@ -53,5 +53,5 @@ jobs:
           key: maven-repo-${{ runner.os }}-${{ steps.get-date.outputs.date }}

       - name: Build with Maven
-        run: mvn -B formatter:validate verify --file pom.xml
+        run: mvn -B formatter:validate verify -Dnative --file pom.xml


This should be done in a different job, so that we can run both native and jvm tests to make sure we cover everything

—
Reply to this email directly, view it on GitHub<https://github.com/quarkiverse/quarkus-operator-sdk/pull/178#pullrequestreview-842558644>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AVDTYHGCQRSJG5U4HLRKRNDUUFPUVANCNFSM5KW4VA5Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-01-03 20:10 UTC, metacosm approved these changes

2022-01-03 20:10 UTC, merged