Support typeless kubernetes resources when generating manifests
quarkiverse/quarkus-operator-sdk pull request #931
Opened 2024-08-22 14:13 UTC by chendouble

Typeless kubernetes resource has no Group and Plural value, so generating wrong policy rule.

Commit summary:
1) Use ApiGroup value from GVK and '*' for Plural value if dependent resource is assignable from GenericKubernetesDependentResource 2) Merge verbs in rule for optimization if with same ApiGroups and Resources

2024-08-23 16:53 UTC, metacosm requested changes

2024-08-23 16:53 UTC, metacosm commented on core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
> +    private static Set<PolicyRule> getNormalizedRules(Set<PolicyRule> collectedRules) {
Can you add tests for this method and maybe add more comments about what it's doing?

2024-08-23 16:54 UTC, metacosm commented on core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java
> +                    rules.stream().filter(rule -> rule.getApiGroups().equals(List.of(TypelessKubeResource.GROUP)))
This is missing an assertion.

2024-08-23 16:55 UTC, metacosm commented
Generally speaking, I will have some improvements, especially after https://github.com/operator-framework/java-operator-sdk/pull/2515 is available in a release, as this will be more precise.

2024-08-23 22:25 UTC, chendouble commented
> Generally speaking, I will have some improvements, especially after [operator-framework/java-operator-sdk#2515](https://github.com/operator-framework/java-operator-sdk/pull/2515) is available in a release, as this will be more precise.

I agree.

2024-08-24 08:47 UTC, metacosm commented
Thank you for the improvements. However, I think that the merging of rules targeting the same apiGroup/kind should be done while we're gathering them, not after, as this would be clearer to understand, in my opinion. Would you mind modifying your PR to do that?

2024-08-24 15:09 UTC, chendouble commented
Maybe the naming is the key, not about before or after.

2024-08-26 09:26 UTC, metacosm approved these changes
Thank you!

2024-08-26 09:27 UTC, merged